RNInageApp/Models/ErrorViewModel.cs
namespace RNInageApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

RNInageApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using RNInageApp.Models;
using System.Diagnostics;

namespace RNInageApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

RNInageApp/Controllers/MyMvcAppController.cs
using Microsoft.AspNetCore.Mvc;

namespace RNInageApp.Controllers
{
    public class MyMvcAppController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public IActionResult UploadImage()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> ClassifyImage(IFormFile imageFile)
        {
            if (imageFile == null || imageFile.Length == 0)
            {
                ViewBag.Message = "Du glömde nog att lägga till en bild";
                return View("UploadImage");
            }
            // konvertera bilden till en bytearray
            byte[] imageBytes;
            using (var memoryStream = new MemoryStream())
            {
                await imageFile.CopyToAsync(memoryStream);
                imageBytes = memoryStream.ToArray();
            }
            // Skapa en modelinput och sätta en bildkälla
            var modelInput = new BildKlassModel.ModelInput
            {
                ImageSource = imageBytes
            };
            //Använd denna modellen för att göra en forutsägelse
            var prediction = BildKlassModel.Predict(modelInput);
            //Hämta och visa resultatet
            ViewBag.PredictionLabel = prediction.PredictedLabel;
            ViewBag.Scores = BildKlassModel.GetSortedScoresWithLabels(prediction);

            return View("UploadImage");
        }
    }
}

RNInageApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

RNInageApp/Views/MyMvcApp/UploadImage.cshtml
@{
    ViewBag.Title = "Bild klassificering";
}
<h2>Ladda upp en bild</h2>
<form asp-action="ClassifyImage" method="post" enctype="multipart/form-data">
    <input type="file" name="imageFile"/>
    <input type="submit" value="Ladda upp och klassificera"/>
</form>

@if (ViewBag.PredictionLabel != null)
{
    <h3>Predicted label: @ViewBag.PredictionLabel</h3>
    <h4>Scores:</h4>
    <ul>
        @foreach (var score in ViewBag.Scores)
        {
            <li>@score.Key: @score.Value</li>
        }
    </ul>
}

RNInageApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RNInageApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RNInageApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RNInageApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="MyMvcApp" asp-action="UploadImage">Bildsök</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - RNInageApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>